# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Reet Lago
description: "Writings of Reet Lago: essays, lyrics, novels, poetry."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://reetlago.github.io" # the base hostname & protocol for your site
history_url: "https://github.com/reetlago/reetlago.github.io/commits/master/"
twitter_username: reetlago
github_username:  reetlago

# Build settings
markdown: kramdown

# Defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      author: Reet Lago

# Don't generate these in _site
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - SETUP
  - TODO

# Even though it's in the Gemfile, without this the sitemap is not generated
gems:
  - jekyll-sitemap
